---
title: Is There a Need for Mainstream Graph-Based Note-Taking Tools?
description: "Exploring why graph-based note-taking apps lack mainstream appeal despite their popularity among certain niche groups and discussing the features that make a tool mainstream."
date: '2023-02-08'
date-modified: '2023-02-08'
categories: [Opinion, PKM, Writing]
---

Unpopular opinion: I agree with [@fortelabs](https://twitter.com/fortelabs/) [here](https://twitter.com/fortelabs/1616173350778441729).

::: {.callout-note title="Tiago Forte talks about graph based PKM apps" collapse="true"}
{{< tweet fortelabs 1616173350778441729 >}}
:::

#### Mass adoption vs niche-critical

Mass adoption of a tool is very different than "niche" critical. As someone who loves organization, I love delving into new apps. I love all the innovation that has been popping up with these apps.

##### Definition

Let's define these terms first:

- What is critical mass? That would be the amount of people using the tool needed for the toool to survive amongst the competitors in its niche areas.

- What is a mainstream tool? It solves a problem that people have and is something that is a go-to for solving that problem.

##### Examples

Now before you come at me, for all those people who love note-taking, consider this. If someone asks you for a habit tracking tool, what do you suggest? Not an "all-in-one" tool, a specific app.

Say @Habitifyapp or @habitica?

Do you think better habit trackers don't exist?
Or someone asks for a journal app. Not an all in one app (for all you obsidian and notion people out there), but for journaling.

Did you suggest @dayoneapp or @myjourneyapp?

#### Why does the distinction matter?

Take a moment to think about why that is the case. Why are these tools "everlasting" and popular?
Give me some specific examples you say?

@GoodNotesApp is the go-to solution to the problem of aesthetic, useful, organizable handwritten searchable notes which is why they still exist even though Apple Notes exists.
@snipd_app is the go-to solution of "how do I remember what I heard" in podcasts, and hence, they are solving a "mainstream" problem.
@airtable and @NotionHQ did not become popular because they were doing something "completely unexpected".

They solved the problem of "how do we store data without complicated SQL?" or "what if I want to have notes for my Google Sheets?"
People started using @Spotify because they did not want to buy albums and wanted good recommendations.

Imagine if spotify's tagline was "we generate music playlists based on the mood we infer from your apple health data", it would be cool but not mainstream.
People work/think with people. How often are we in situations where we think/write/document about a "problem" start to end "alone"?

#### What we love vs what public needs

And any tool that is not collaborative or multi-platform lacks the ability to become mainstream. There is a reason @todoist is so popular.
Coming back to the note-taking space. There are many features that us, note-taking people love.

It should have backlinks, should have markdown support, should have magical powers to transform my life when I zoom into the note-web I created.
Ask any random person what they want in a note-taking app and their answer would be: frictionless adding, storage, surfacing, tagging, filtering.

That is why people use Apple Notes. And with minimal difference is why @evernote and @BearNotesApp became popular.

##### Lack of mainstream applications

The biggest problem with graph note-taking apps is the lack of "mainstream" applications.

Most mainstream graph based explorations require automatic content extraction (for example @RsrchRabbit which looks at "graph" of academic papers).

Do I hear you say, "but I love graphs?". I think that is great that you do, but most people do not care about it. Most people who want a visual component to their notes, also want a visual component to the interaction, not use [[ to make a connection.

#### What about spatial canvas applications?

That is one of the main reason why I think @MuseAppHQ, @whimsical and @scrintal are headed in the right direction of "graphs" which is more akin to "whiteboarding" something that people know, that people are used to.

But these are not private. They are not local. They are not based in markdown. If you want all of those, good for you.

#### Older apps are here to stay

But given how many people use Google Docs, MS Word and Apple Notes, it is not hard to infer that people do not care about it.
Am I being delusional? I sure hope so. But more than likely, I am not.

Do you know how many academics still use Latex and @overleaf for their papers (yes, even in CS)?

But even better, do you know how many use MS Word?

You would be surprised!
In summary, all I want to say is as much as I am happy that @tana_inc exists, no it won't kill @NotionHQ, just like Notion did not kill Google Docs.